import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ToastProvider } from '@heroui/toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BookVault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning>
        
        <Navbar />
        <ToastProvider 
          placement="top-right" 
          toastProps={{
            timeout: 3000, 
            radius: "md",
            classNames: {
              // This guarantees it floats above your navbar and doesn't push layout
              base: "fixed top-4 right-4 z-[9999] shadow-lg border border-gray-100", 
            }
          }} 
        />
        {children}
        <Footer />
        
      </body>
    </html>
  );
}
