import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ToastProvider } from '@heroui/toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BookVault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning>
        
        <Navbar />
        <ToastProvider 
                  position="top-right" 
                  maxVisibleToasts={2}
                  toastProps={{
                    timeout: 2500,        // Disappears automatically in 2.5 seconds
                    radius: "full",       // Small capsule style that doesn't look blocky
                    variant: "flat",      // Clean, subtle matching color background
                    shouldShowTimeoutProgress: false, // Removes the distracting loading bar
                    classNames: {
                      base: "shadow-md border border-gray-100 backdrop-blur-md bg-white/90 z-[9999] max-w-sm",
                    }
                  }} 
          />
        {children}
        <Footer />
        
      </body>
    </html>
  );
}
